/*Copyright (c) 2017-2018 vanenburgsoftware.com All Rights Reserved.
 This software is the confidential and proprietary information of vanenburgsoftware.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with vanenburgsoftware.com*/
package com.nrd.services;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * BoughtTags generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`BoughtTags`")
public class BoughtTags implements Serializable {

    private String tag;
    private String tagType;
    private Long inUse;
    private String usedFor;
    private String comment;
    private String error;

    @Id
    @Column(name = "`Tag`", nullable = false, length = 15)
    public String getTag() {
        return this.tag;
    }

    public void setTag(String tag) {
        this.tag = tag;
    }

    @Column(name = "`TagType`", nullable = true, length = 10)
    public String getTagType() {
        return this.tagType;
    }

    public void setTagType(String tagType) {
        this.tagType = tagType;
    }

    @Column(name = "`InUse`", nullable = true, scale = 0, precision = 10)
    public Long getInUse() {
        return this.inUse;
    }

    public void setInUse(Long inUse) {
        this.inUse = inUse;
    }

    @Column(name = "`UsedFor`", nullable = true, length = 35)
    public String getUsedFor() {
        return this.usedFor;
    }

    public void setUsedFor(String usedFor) {
        this.usedFor = usedFor;
    }

    @Column(name = "`Comment`", nullable = true, length = 100)
    public String getComment() {
        return this.comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    @Column(name = "`Error`", nullable = true, length = 100)
    public String getError() {
        return this.error;
    }

    public void setError(String error) {
        this.error = error;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof BoughtTags)) return false;
        final BoughtTags boughtTags = (BoughtTags) o;
        return Objects.equals(getTag(), boughtTags.getTag());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getTag());
    }
}

