/*Copyright (c) 2017-2018 vanenburgsoftware.com All Rights Reserved.
 This software is the confidential and proprietary information of vanenburgsoftware.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with vanenburgsoftware.com*/
package com.nrd.services;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TreeSpecies generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`TreeSpecies`")
public class TreeSpecies implements Serializable {

    private String specieCode;
    private String scientificName;
    private Long minimumDbh;

    @Id
    @Column(name = "`SpecieCode`", nullable = false, length = 10)
    public String getSpecieCode() {
        return this.specieCode;
    }

    public void setSpecieCode(String specieCode) {
        this.specieCode = specieCode;
    }

    @Column(name = "`ScientificName`", nullable = true, length = 255)
    public String getScientificName() {
        return this.scientificName;
    }

    public void setScientificName(String scientificName) {
        this.scientificName = scientificName;
    }

    @Column(name = "`MinimumDBH`", nullable = true, scale = 0, precision = 10)
    public Long getMinimumDbh() {
        return this.minimumDbh;
    }

    public void setMinimumDbh(Long minimumDbh) {
        this.minimumDbh = minimumDbh;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof TreeSpecies)) return false;
        final TreeSpecies treeSpecies = (TreeSpecies) o;
        return Objects.equals(getSpecieCode(), treeSpecies.getSpecieCode());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getSpecieCode());
    }
}

