/*Copyright (c) 2017-2018 vanenburgsoftware.com All Rights Reserved.
 This software is the confidential and proprietary information of vanenburgsoftware.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with vanenburgsoftware.com*/
package com.nrd.services;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.sql.Date;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.wavemaker.runtime.data.annotations.ServerDefinedProperty;
import com.wavemaker.runtime.data.replacers.Scope;
import com.wavemaker.runtime.data.replacers.providers.VariableType;

/**
 * TreeEnumerations generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`TreeEnumerations`")
public class TreeEnumerations implements Serializable {

    private String treeTag;
    private String specieCode;
    private Date enumerationDate;
    private String enumerationType;
    private String scanningPerson;
    private String block;
    private Long estimatedHeight;
    private Long estimatedDiameter;
    private String device;
    private String enumerationResult;
    private Date createdDate;
    @ServerDefinedProperty( value = VariableType.USER_NAME, scopes = { Scope.INSERT, Scope.UPDATE })
    private String createdBy;
    private Date modifiedDate;
    @ServerDefinedProperty( value = VariableType.USER_NAME, scopes = { Scope.INSERT, Scope.UPDATE })
    private String modifiedBy;
    private TreeSpecies treeSpecies;
    private Employee employee;

    @Id
    @Column(name = "`treeTag`", nullable = false, length = 15)
    public String getTreeTag() {
        return this.treeTag;
    }

    public void setTreeTag(String treeTag) {
        this.treeTag = treeTag;
    }

    @Column(name = "`SpecieCode`", nullable = false, length = 255)
    public String getSpecieCode() {
        return this.specieCode;
    }

    public void setSpecieCode(String specieCode) {
        this.specieCode = specieCode;
    }

    @Column(name = "`EnumerationDate`", nullable = true)
    public Date getEnumerationDate() {
        return this.enumerationDate;
    }

    public void setEnumerationDate(Date enumerationDate) {
        this.enumerationDate = enumerationDate;
    }

    @Column(name = "`EnumerationType`", nullable = true, length = 255)
    public String getEnumerationType() {
        return this.enumerationType;
    }

    public void setEnumerationType(String enumerationType) {
        this.enumerationType = enumerationType;
    }

    @Column(name = "`ScanningPerson`", nullable = true, length = 255)
    public String getScanningPerson() {
        return this.scanningPerson;
    }

    public void setScanningPerson(String scanningPerson) {
        this.scanningPerson = scanningPerson;
    }

    @Column(name = "`Block`", nullable = true, length = 255)
    public String getBlock() {
        return this.block;
    }

    public void setBlock(String block) {
        this.block = block;
    }

    @Column(name = "`Estimated height`", nullable = true, scale = 0, precision = 10)
    public Long getEstimatedHeight() {
        return this.estimatedHeight;
    }

    public void setEstimatedHeight(Long estimatedHeight) {
        this.estimatedHeight = estimatedHeight;
    }

    @Column(name = "`Estimated diameter`", nullable = true, scale = 0, precision = 10)
    public Long getEstimatedDiameter() {
        return this.estimatedDiameter;
    }

    public void setEstimatedDiameter(Long estimatedDiameter) {
        this.estimatedDiameter = estimatedDiameter;
    }

    @Column(name = "`Device`", nullable = true, updatable = false, length = 255)
    public String getDevice() {
        return this.device;
    }

    public void setDevice(String device) {
        this.device = device;
    }

    @Column(name = "`EnumerationResult`", nullable = true, length = 500)
    public String getEnumerationResult() {
        return this.enumerationResult;
    }

    public void setEnumerationResult(String enumerationResult) {
        this.enumerationResult = enumerationResult;
    }

    @Column(name = "`CreatedDate`", nullable = true, updatable = false)
    public Date getCreatedDate() {
        return this.createdDate;
    }

    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    @Column(name = "`CreatedBy`", nullable = true, length = 255)
    public String getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Column(name = "`ModifiedDate`", nullable = true)
    public Date getModifiedDate() {
        return this.modifiedDate;
    }

    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

    @Column(name = "`ModifiedBy`", nullable = true, length = 255)
    public String getModifiedBy() {
        return this.modifiedBy;
    }

    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "`SpecieCode`", referencedColumnName = "`SpecieCode`", insertable = false, updatable = false)
    public TreeSpecies getTreeSpecies() {
        return this.treeSpecies;
    }

    public void setTreeSpecies(TreeSpecies treeSpecies) {
        if(treeSpecies != null) {
            this.specieCode = treeSpecies.getSpecieCode();
        }

        this.treeSpecies = treeSpecies;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "`ScanningPerson`", referencedColumnName = "`EmployeeName`", insertable = false, updatable = false)
    public Employee getEmployee() {
        return this.employee;
    }

    public void setEmployee(Employee employee) {
        if(employee != null) {
            this.scanningPerson = employee.getEmployeeName();
        }

        this.employee = employee;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof TreeEnumerations)) return false;
        final TreeEnumerations treeEnumerations = (TreeEnumerations) o;
        return Objects.equals(getTreeTag(), treeEnumerations.getTreeTag());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getTreeTag());
    }
}

